### 1. Importing TensorFlow & Checking Version

In [ ]:
import tensorflow as tf

In [46]:
print(tf.__version__)

2.19.0


### 2. Creating Basic Tensors

In [ ]:
scalar = tf.constant(9)               # Scalar (0D) → just one number
vector = tf.constant([10,10])         # Vector (1D) → line of numbers
matrix = tf.constant([[10,7],[7,10]]) # Matrix (2D) → table of numbers

In [ ]:
scalar.ndim, vector.ndim, matrix.ndim
➡️ Shows number of dimensions (rank).

In [47]:
# Creates a TensorFlow constant tensor
# tf.constant() is a function in TensorFlow used for creating tensors with a fixed value
scalar = tf.constant(9)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=9>

In [48]:
# accesses the ndim attribute of the scalar tensor, which returns the number of dimensions of the tensor. A scalar tensor has 0 dimensions.
scalar.ndim

0

In [49]:
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [50]:
vector.ndim # .ndim tells you how many axes/dimensions a tensor has

1

In [51]:
matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [52]:
matrix.ndim

2

In [53]:
second_matrix = tf.constant(
    [[10.,7.],
     [3.,2.],
     [8.,9.]],dtype=tf.float16)
second_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

### 3. Higher-Dimensional Tensors

In [ ]:
third_matrix=tf.constant([
        [[1,2,3],[4,5,6]],
        [[7,8,9],[10,11,12]]
])
display(third_matrix)

In [56]:
# a 2-D array of numbers
matrix=tf.constant([[10,20], [30,40]])
display(matrix)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

In [57]:
#Tensor : an n-dimensional array of numbers (n=0,n=1,n=2.........)
tensor=tf.constant([[[1,2], [3,4]], [ [5,6], [7, 8]]])
tensor

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]], dtype=int32)>

### 4. Inspecting Tensor Properties

In [58]:
# Find the shape, dimension, rank and size of the tensors
print("Scalar Information")
print("Shape:",scalar.shape)
print("Dimension: ",scalar.ndim)
print("Rank: ",tf.rank(scalar).numpy())
print("Size: ",tf.size(scalar))

Scalar Information
Shape: ()
Dimension:  0
Rank:  0
Size:  tf.Tensor(1, shape=(), dtype=int32)


In [59]:
print("Vector Information")
print("Shape:", vector.shape)
print("Dimension: ",vector.ndim)
print("Rank: ",tf.rank(vector).numpy())
print("Size: ",tf.size(vector))

Vector Information
Shape: (2,)
Dimension:  1
Rank:  1
Size:  tf.Tensor(2, shape=(), dtype=int32)


In [60]:
print("Matrix Information")
print("Shape:",matrix.shape)
print("Dimension: ",matrix.ndim)
print("Rank: ",tf.rank(matrix) .numpy())
print("Size: ",tf.size(matrix))

Matrix Information
Shape: (2, 2)
Dimension:  2
Rank:  2
Size:  tf.Tensor(4, shape=(), dtype=int32)


In [62]:
print("Tensor Information")
print("Shape:",tensor.shape)
print("Dimension: ",tensor.ndim)
print("Rank: ",tf.rank(tensor) .numpy())
print("Size: ",tf.size(tensor))

Tensor Information
Shape: (2, 2, 2)
Dimension:  3
Rank:  3
Size:  tf.Tensor(8, shape=(), dtype=int32)


### 5. Difference Between Constant and Variable

In [63]:
#Creating Tensor using Varibale
changeable_tensor=tf.Variable([10,7])
unchangeable_tensor=tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [64]:
changeable_tensor[0].assign(9)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([9, 7], dtype=int32)>

In [65]:
changeable_tensor[1].assign(15)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 9, 15], dtype=int32)>

In [66]:
changeable_tensor[1].assign(75)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 9, 75], dtype=int32)>

In [69]:
# unchangeable_tensor[0].assign(12)
# unchangeable_tensor
# this will be an error because you can't change constant tensor. They are Immutable i.e. unchangable

### 6. Random Tensors

In [73]:
#Random Tensors
random_tensor=tf.random.Generator.from_seed(7887)
random_tensor=random_tensor.normal(shape=(5,3))
random_tensor

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[-0.43810788,  0.28429744, -0.5409136 ],
       [-1.4620612 ,  0.47750482, -0.26694295],
       [ 0.7458992 , -0.81563425, -0.79668176],
       [-1.4223062 , -0.83481544,  0.03400012],
       [-0.3457154 , -0.9288432 , -0.7159353 ]], dtype=float32)>

In [74]:
random_tensor_2=tf.random.uniform(shape=(300,150),minval=0,maxval=1)
random_tensor_2

<tf.Tensor: shape=(300, 150), dtype=float32, numpy=
array([[0.41916847, 0.55720437, 0.38695323, ..., 0.19198298, 0.88208675,
        0.09114504],
       [0.434888  , 0.1143862 , 0.7614008 , ..., 0.6441523 , 0.24896061,
        0.01175439],
       [0.22751951, 0.09255409, 0.93071115, ..., 0.33425522, 0.36449337,
        0.30310333],
       ...,
       [0.88453615, 0.8684051 , 0.7903501 , ..., 0.07401097, 0.22555304,
        0.7213154 ],
       [0.31170988, 0.56196237, 0.21912146, ..., 0.79916704, 0.96145535,
        0.6318437 ],
       [0.9991518 , 0.9637935 , 0.94023705, ..., 0.31018937, 0.13301349,
        0.9903687 ]], dtype=float32)>

In [75]:
# same seed same tensors
random_tensor_3=tf.random.Generator.from_seed(42)
random_tensor_3=random_tensor_3.normal(shape=(3,2))
random_tensor_4=tf.random.Generator.from_seed(42)
random_tensor_4 = random_tensor_4.normal(shape=(3,2))
random_tensor_3,random_tensor_4

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>)

In [76]:
#different seed different tesnsors
random_tensor_3=tf.random.Generator.from_seed(42)
random_tensor_3=random_tensor_3.normal(shape=(3,2))
random_tensor_4=tf.random. Generator. from_seed(15)
random_tensor_4 = random_tensor_4.normal(shape=(3,2))
random_tensor_3, random_tensor_4

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.33149973, -0.5445254 ],
        [ 1.5222508 ,  0.59303206],
        [-0.63509274,  0.3703566 ]], dtype=float32)>)

### 7. Zeroes, Ones, and Basic Initialization

In [79]:
#creating tensors using zeors (Integer)
tensor_zeros=tf.zeros(shape=(3,4), dtype = tf.dtypes.int16)
tensor_zeros

<tf.Tensor: shape=(3, 4), dtype=int16, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int16)>

In [80]:
#creating tensors using zeors Float)
tensor_zeros=tf.zeros(shape=(3,4), dtype = tf.dtypes.float32)
tensor_zeros

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [81]:
#creating tensors all ones
tensor_ones=tf.ones(shape=(3,4), dtype = tf.dtypes.int16)
tensor_ones

<tf.Tensor: shape=(3, 4), dtype=int16, numpy=
array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)>

### 8. Basic Tensor Operations

In [82]:
# Basic Tensor Operations
# Tensors behave like super-charged NumPy arrays.
a = tf.constant([[1, 2],
                 [3, 4]])

b = tf.constant([[5, 6],
                 [7, 8]])

print(a + b)  # element-wise addition
print(a * b)  # element-wise multiplication
print(tf.matmul(a, b))  # matrix multiplication


tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


### 9. Converting from NumPy

In [83]:
import numpy as np
numpy_Array=np.arange(1,25,dtype=np.int16)
numpy_Array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int16)

In [84]:
tensor_numpy=tf.constant(numpy_Array, shape=(2,3,4))
tensor_numpy

<tf.Tensor: shape=(2, 3, 4), dtype=int16, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int16)>

In [87]:
print("Tesnor Information")
print("Shape:", tensor_numpy. shape)
print("Dimension: ", tensor_numpy.ndim)
print("Rank: ",tf.rank(tensor_numpy) . numpy())
print("Size: ",tf.size(tensor_numpy))
print("DataType of elements: ",tensor_numpy.dtype)
print("Element along axis 0: ",tensor_numpy.shape[0])
print("Element along axis 1: ",tensor_numpy.shape[1])
print("Element along axis 2: ",tensor_numpy.shape[2])
print("Elements along all axes: ",tf.size(tensor_numpy).numpy())

Tesnor Information
Shape: (2, 3, 4)
Dimension:  3
Rank:  3
Size:  tf.Tensor(24, shape=(), dtype=int32)
DataType of elements:  <dtype: 'int16'>
Element along axis 0:  2
Element along axis 1:  3
Element along axis 2:  4
Elements along all axes:  24


### 10. Indexing and Slicing

In [91]:
#Working with items of each dimension
# First three elements
tensor_numpy [ :3, :3, :3]

<tf.Tensor: shape=(2, 3, 3), dtype=int16, numpy=
array([[[ 1,  2,  3],
        [ 5,  6,  7],
        [ 9, 10, 11]],

       [[13, 14, 15],
        [17, 18, 19],
        [21, 22, 23]]], dtype=int16)>

In [90]:
# firs elements of each dimension
tensor_numpy[:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2), dtype=int16, numpy=
array([[[ 1,  2],
        [ 5,  6]],

       [[13, 14],
        [17, 18]]], dtype=int16)>

Arthmetic Operations with Tensors

- Add
- Sub
- Multi
- Div

In [95]:
tensor_one = tf.constant([[11,9], [2,5]])
tensor_one

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11,  9],
       [ 2,  5]], dtype=int32)>

### 11. Arithmetic with Tensors

In [100]:
# tensor_one + 10
tf.add(tensor_one,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[21, 19],
       [12, 15]], dtype=int32)>

In [97]:
tensor_one - 10
# tf.subtract(tensor_one,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1, -1],
       [-8, -5]], dtype=int32)>

In [98]:
tensor_one * 10
# tf.multiply(tensor_one,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[110,  90],
       [ 20,  50]], dtype=int32)>

In [99]:
tensor_one / 10
# tf.divide(tensor_one,10)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1.1, 0.9],
       [0.2, 0.5]])>

In [105]:
tensor_new=tf.square(tensor_one)
tensor_new

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  81],
       [  4,  25]], dtype=int32)>

In [106]:
second_matrix=tf.constant([[8,16], [64,8.25],
[625,9.23],
[125,2.34],
[169,144]], dtype=tf.float32)

print(second_matrix)

tf.Tensor(
[[  8.    16.  ]
 [ 64.     8.25]
 [625.     9.23]
 [125.     2.34]
 [169.   144.  ]], shape=(5, 2), dtype=float32)


In [107]:
tf.sqrt(second_matrix)

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[ 2.828427 ,  4.       ],
       [ 8.       ,  2.8722813],
       [25.       ,  3.0380914],
       [11.18034  ,  1.5297059],
       [13.       , 12.       ]], dtype=float32)>

### Exercise
Create two tensors with random values between 0 and 1 , shape is [6,
300]
##### Find out the following details:
- Size (Number of elements)
- Rank
- Shape

In [114]:
random_tensor_1=tf.random.uniform(shape=(6,300),minval=0,maxval=1)
random_tensor_2=tf.random.uniform(shape=(6,300),minval=0,maxval=1)

print("Tensor 1 Information")
print("Size (number of elements):", tf.size(random_tensor_1).numpy()) # Total count of values in the tensor → 6 × 300
print("Rank:", tf.rank(random_tensor_1).numpy()) # Number of dimensions
print("Shape:", random_tensor_1.shape) # How the data is arranged (rows, columns, etc.)

print("\nTensor 2 Information")
print("Size (number of elements):", tf.size(random_tensor_2).numpy())
print("Rank:", tf.rank(random_tensor_2).numpy())
print("Shape:", random_tensor_2.shape)

Tensor 1 Information
Size (number of elements): 1800
Rank: 2
Shape: (6, 300)

Tensor 2 Information
Size (number of elements): 1800
Rank: 2
Shape: (6, 300)
