In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_excel('students.xlsx')
print(df)

    Name  Age  Marks
0   John   20     85
1  Alice   22     90
2    Bob   21     78
3   Sara   23     92
4    Sam   25     90
5  Rohit   23     45


In [4]:
marks=df['Marks'].to_numpy()
print('Numpy Array of Marks')
print(marks)

Numpy Array of Marks
[85 90 78 92 90 45]


In [25]:
print('Highest Marks ',np.max(marks))

Highest Marks  92


In [26]:
print('Lowest Marks ',np.min(marks))

Lowest Marks  45


In [27]:
print('Average Marks ',np.mean(marks))

Average Marks  80.0


# .loc: Label Based
# .iloc: Index Based

In [10]:
print('original dataframe')
print(df)
print('Location : Label Based')
print(df.loc[2,['Name','Marks']])

original dataframe
    Name  Age  Marks
0   John   20     85
1  Alice   22     90
2    Bob   21     78
3   Sara   23     92
4    Sam   25     90
5  Rohit   23     45
Location : Label Based
Name     Bob
Marks     78
Name: 2, dtype: object


In [9]:
print('original dataframe')
print(df)
print('Location : Index Based')
print(df.iloc[2,[1,2]])

original dataframe
    Name  Age  Marks
0   John   20     85
1  Alice   22     90
2    Bob   21     78
3   Sara   23     92
4    Sam   25     90
5  Rohit   23     45
Location : Index Based
Age      21
Marks    78
Name: 2, dtype: object


# Axis in Numpy : 
    1. Axis 0 : vertical direction works column-wise   
    2. Axis 1 : horizontal direction: works row-wise

# We have two students' marks in three subjects
[[45,50,49],[30,45,49]]

In [11]:
marks_arr=np.array([[45,50,49],[30,45,49]])
print(marks_arr)

[[45 50 49]
 [30 45 49]]


##### 📘 Axis 0 → column-wise (top to bottom)

In [12]:
print('Sum down each column',np.sum(marks_arr,axis=0))

Sum down each column [75 95 98]


##### 📘 Axis 1 → row-wise (left to right)

In [13]:
print('Sum down each row',np.sum(marks_arr,axis=1))

Sum down each row [144 124]


In [14]:
print('Numpy Array of Marks')
print(marks)

Numpy Array of Marks
[85 90 78 92 90 45]


In [15]:
print(df)

    Name  Age  Marks
0   John   20     85
1  Alice   22     90
2    Bob   21     78
3   Sara   23     92
4    Sam   25     90
5  Rohit   23     45


# Find the student name who got highest mark

In [17]:
topper=df.loc[df['Marks'].idxmax(),'Name']
print('Topper Student Name',topper)

Topper Student Name Sara


In [18]:
dir(df['Marks'])

['T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__bool__',
 '__class__',
 '__column_consortium_standard__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__firstlineno__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pandas_priority__',
 '__pos__',
 '__pow__',
 '_

In [19]:
help(df['Marks'].idxmax)

Help on method idxmax in module pandas.core.series:

idxmax(axis: 'Axis' = 0, skipna: 'bool' = True, *args, **kwargs) -> 'Hashable' method of pandas.core.series.Series instance
    Return the row label of the maximum value.

    If multiple values equal the maximum, the first row label with that
    value is returned.

    Parameters
    ----------
    axis : {0 or 'index'}
        Unused. Parameter needed for compatibility with DataFrame.
    skipna : bool, default True
        Exclude NA/null values. If the entire Series is NA, the result
        will be NA.
    *args, **kwargs
        Additional arguments and keywords have no effect but might be
        accepted for compatibility with NumPy.

    Returns
    -------
    Index
        Label of the maximum value.

    Raises
    ------
    ValueError
        If the Series is empty.

    See Also
    --------
    numpy.argmax : Return indices of the maximum values
        along the given axis.
    DataFrame.idxmax : Return index of fir

In [20]:
lastinclass=df.loc[df['Marks'].idxmin(),'Name']
print(lastinclass)

Rohit


In [21]:
print('Next Example')

Next Example


In [28]:
top_index = df['Marks'].idxmax()
top_student=df.iloc[top_index,df.columns.get_loc('Name')]
print('Topper of the class is: ',top_student)

Topper of the class is:  Sara


| Step                         | Purpose                         | Example Result                 |
| ---------------------------- | ------------------------------- | ------------------------------ |
| `df['Marks'].idxmax()`       | Find index of highest marks     | `1`                            |
| `df.columns.get_loc('Name')` | Find position of “Name” column  | `0`                            |
| `df.iloc[...]`               | Select that cell (row 1, col 0) | `"Bala"`                       |
| `print(...)`                 | Show the result                 | “Topper of the class is: Bala” |


##### 💬 Plain English version:

“Look at the Marks column, find the row with the highest mark,
then go to that row and read the student’s Name.”

    # df.iloc[row_index, column_index] → takes row first, then column.

    # op_index is the row index (for the student with highest marks).

    # df.columns.get_loc('Name') gives the column index number for 'Name'.
    So together, this means “find the value at (row = top student, column = Name).”

💡 Summary:

| Method  | Type                  | Syntax Example               | Uses                       |
| ------- | --------------------- | ---------------------------- | -------------------------- |
| `.iloc` | index-based (numbers) | `df.iloc[2, 1]`              | Row 2, Col 1               |
| `.loc`  | label-based (names)   | `df.loc['RowLabel', 'Name']` | Row “RowLabel”, Col “Name” |
