# Numpy Introduction and Usage
## We will use numpy in this Jupyter notebook
## One-Dimensional Array (1-D)

In [68]:
import numpy as np

In [3]:
array1=np.array([10,20,30,40,50,80])

In [4]:
print(array1)

[10 20 30 40 50 80]


# Two-Dimensional Array (2-D)

In [5]:
array_two=np.array([[10,20,30],[40,50,70]])

In [6]:
print(array_two)

[[10 20 30]
 [40 50 70]]


# Three Dimensional Array ( 3-D Array)

In [7]:
array_three=np.array([[[10,20,30],[40,50,70]],[[10,20,30],[40,50,70]]])

In [8]:
print(array_three)

[[[10 20 30]
  [40 50 70]]

 [[10 20 30]
  [40 50 70]]]


# Find out Dimension of NumPy array

In [9]:
print('First Array Dimension: \t', array1.ndim)

First Array Dimension: 	 1


In [10]:
print('Second Array Dimension: \t', array_two.ndim)

Second Array Dimension: 	 2


In [11]:
print('Third Array Dimension: \t', array_three.ndim)

Third Array Dimension: 	 3


# Write an array of 5 student's using Numpy
    ## Marks are: 80,70,75,99,89

In [12]:
array_marks=np.array([80,70,75,99,89,90])
print('Array of Marks:')
print(array_marks)

Array of Marks:
[80 70 75 99 89 90]


# Write an array: to take the Marks of 5 students in 3 subjects using Numpy

## Math, English, Chemistry

## [[50,45,49],[40,42,45],[35,40,46],[39,40,45],[48,40,40]]

In [13]:
marks_subject=np.array([[50,45,49],[40,42,45],[35,40,46],[39,40,45],[48,40,40]])
print('2 D Array Example')
print(marks_subject)

2 D Array Example
[[50 45 49]
 [40 42 45]
 [35 40 46]
 [39 40 45]
 [48 40 40]]


# Write an array: to take Marks of 4 students in 3 subjects for two semester using Numpy
     ## Students Name are: 'Amit','Sha','Xi','Arif'
     ## Math, English, Chemistry
     ## Two Semester : Sem1 , Sem2
     ## 4*3*2 (The Array)
     ## ([[[85, 88],[78, 82],[90, 95]] , [[76, 70],[40, 45],[90, 90]] ,[[80, 86],[78, 82],[90, 95]],[[85, 88],[78, 82],[70, 90]]])

In [14]:
marks_subject_sem=np.array([
    [[85, 88],[78, 82],[90, 95]], 
    [[76, 70],[40, 45],[90, 90]],
    [[80, 86],[78, 82],[90, 95]],
    [[85, 88],[78, 82],[70, 90]]
])

In [15]:
print (marks_subject_sem)

[[[85 88]
  [78 82]
  [90 95]]

 [[76 70]
  [40 45]
  [90 90]]

 [[80 86]
  [78 82]
  [90 95]]

 [[85 88]
  [78 82]
  [70 90]]]


# Write an array: to take wheather of 2 cities in 3 days for three times in a day for morning, noon ,evening
    ## Cities Name are: Kuala Lumpur, Delhi
    ## Saturday, Sunday, Monday
    ## Three Time Slot : Morning, Noon, Evening
    ## Kuala Lumpur :[[25,30,28],[24,28,25],[30,32,30]]
    ## Delhi:[[30,35,30],[32,34,30],[28,31,30]]
    ## [[[25,30,28],[24,28,25],[30,32,30]],[[30,35,30],[32,34,30],[28,31,30]]]

### Create one 3D Array for this using NumPy and print it

In [16]:
wheather_array=np.array([[[25,30,28],[24,28,25],[30,32,30]],[[30,35,30],[32,34,30],[28,31,30]]])

In [17]:
print(wheather_array)

[[[25 30 28]
  [24 28 25]
  [30 32 30]]

 [[30 35 30]
  [32 34 30]
  [28 31 30]]]


# Basic Information
    ## shape: rows and columns
    ## Size: number of elements
    ## Dimension: return dimension 1, 2, 3....
    ## Data Type: return stored data values type

In [18]:
print(array1)

[10 20 30 40 50 80]


In [19]:
print("Shape of array1 : ",array1.shape)

Shape of array1 :  (6,)


In [20]:
print("Size of array1 : ",array1.size)

Size of array1 :  6


In [21]:
print ('Dimension: ',array1.ndim)

Dimension:  1


In [22]:
print ('Data Type: ',array1.dtype)

Data Type:  int64


In [23]:
students=np.array(['Ali Munaf Bin Kabir','Shi','Xi','Meena','Ziva'])

In [24]:
print(students)

['Ali Munaf Bin Kabir' 'Shi' 'Xi' 'Meena' 'Ziva']


In [25]:
print("Shape of Array : ",students.shape)

Shape of Array :  (5,)


In [26]:
print('Number of students',students.size)

Number of students 5


In [27]:
print('Data Type: ',students.dtype)

Data Type:  <U19


# Mathematical Operation

In [28]:
print(array1)

[10 20 30 40 50 80]


In [29]:
total=np.sum(array1)

In [30]:
print(total)

230


In [31]:
print('Mean: ',np.mean(array1))

Mean:  38.333333333333336


In [32]:
print('Min: ',np.min(array1))

Min:  10


In [33]:
print('Max: ',np.max(array1))

Max:  80


In [34]:
print('The Min is at Index: ',np.argmin(array1))

The Min is at Index:  0


In [35]:
print('The Max is at Index: ',np.argmax(array1))

The Max is at Index:  5


In [36]:
our_arr=np.array([100,200,300,7000,400,500,300,1900,600])

In [37]:
print(our_arr)

[ 100  200  300 7000  400  500  300 1900  600]


# Searching and Sorting Example in 1D Array

In [38]:
sorted_arr=np.sort(our_arr)
print('*** Sorted Array ')
print(sorted_arr)

*** Sorted Array 
[ 100  200  300  300  400  500  600 1900 7000]


In [39]:
print('Is there any item greater than 500 ?: ',np.any(sorted_arr>500))

Is there any item greater than 500 ?:  True


In [40]:
print('All greater than 500 ?: ',np.all(sorted_arr>500))

All greater than 500 ?:  False


In [41]:
print('All greater than 99 ?: ',np.all(sorted_arr>99))

All greater than 99 ?:  True


In [42]:
print('Where values >500',np.where(sorted_arr>500))

Where values >500 (array([6, 7, 8]),)


In [43]:
print('All Number greater than 500')
for num in np.where(sorted_arr>500):
    print (num)

All Number greater than 500
[6 7 8]


In [44]:
print(our_arr)

[ 100  200  300 7000  400  500  300 1900  600]


In [45]:
print(np.min(our_arr))

100


In [46]:
print('Index of Min: ',np.argmin(our_arr))

Index of Min:  0


In [47]:
print('Index of Max',np.argmax(sorted_arr))

Index of Max 8


In [48]:
print('All Number greater than 500')
for num in sorted_arr>500:
    print (num)

All Number greater than 500
False
False
False
False
False
False
True
True
True


In [49]:
selected_values=sorted_arr[sorted_arr>500]

In [50]:
print(selected_values)

[ 600 1900 7000]


In [51]:
for num in selected_values:
    print (num)

600
1900
7000


In [52]:
for num in sorted_arr[sorted_arr>500]:
    print(num)

600
1900
7000


In [53]:
print(' ',sorted_arr[sorted_arr>500])

  [ 600 1900 7000]


# Slicing 1 D Array
    1. To take elements from an index (included) to an index (not included)
    2. e.g. [start:end]

In [54]:
print(sorted_arr)

[ 100  200  300  300  400  500  600 1900 7000]


In [55]:
slice_sorted_arr=sorted_arr[1:3]
print(slice_sorted_arr)

[200 300]


# Starting from an index and going till the last

In [56]:
sorted_arr

array([ 100,  200,  300,  300,  400,  500,  600, 1900, 7000])

### print(sorted_arr[3:])

In [57]:
print("This will start from index 3, and take everything after it:", sorted_arr[3:])

This will start from index 3, and take everything after it: [ 300  400  500  600 1900 7000]


### print(sorted_arr[:4])

In [58]:
print('This will take everything from the beginning up to index 4 (not including 4)',sorted_arr[:4])

This will take everything from the beginning up to index 4 (not including 4) [100 200 300 300]


### print(sorted_arr[:5])

In [59]:
print('This will take everything from the beginning up to index 5 (not including 5)',sorted_arr[:5])

This will take everything from the beginning up to index 5 (not including 5) [100 200 300 300 400]


# Step
    ## [start:end:step]
    ## step: every step element

In [60]:
our_slice=sorted_arr[1:6:2]
print (our_slice)


[200 300 500]


In [61]:
print('Original Array')
print(sorted_arr)
print('Every Third Element')
every_third_element=sorted_arr[::3]
print(every_third_element)

Original Array
[ 100  200  300  300  400  500  600 1900 7000]
Every Third Element
[100 300 600]


# Slice Reverse

In [62]:
print('Original Array')
print(sorted_arr)
print('Reverse Array: ')
print(sorted_arr[::-1])

Original Array
[ 100  200  300  300  400  500  600 1900 7000]
Reverse Array: 
[7000 1900  600  500  400  300  300  200  100]


In [70]:
print('Last five elements')
print(sorted_arr[::-5])

Last five elements
[7000  300]


In [64]:
print('Slicing is Done')

Slicing is Done


In [74]:
print('In reverse, will step (leave) the second number')
print(sorted_arr[::-2])

In reverse, will step (leave) the second number
[7000  600  400  300  100]


In [75]:
import os, time
path = "NumpyExNotebook.ipynb"
print("Last modified:", time.ctime(os.path.getmtime(path)))


Last modified: Sun Oct 26 17:12:30 2025
